name: UbuntuSSH
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: rokibhasansagar/slimhub_actions@main
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
