name: UbuntuSSH
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: marvelmathesh/dockerfile:rom
    steps:
      - name: Start SSH via tmate
        uses: mxschmitt/action-tmate@master
